---
- name: Create files group
  ansible.builtin.group:
    name: files
    gid: "{{ file_gid }}"
- name: Create files user
  ansible.builtin.user:
    name: files
    uid: "{{ file_uid }}"
    system: true
