---
- name: Get vaultwarden https site certificate
  ansible.builtin.command: '/usr/bin/certbot -n --nginx certonly -d {{ setup_vaultwarden_ssl_service_name }}.{{ setup_vaultwarden_ssl_net_host }}'
  args:
    creates: '/etc/letsencrypt/live/{{ setup_vaultwarden_ssl_service_name }}.{{ setup_vaultwarden_ssl_net_host }}'
  tags: nginx, certbot, vaultwarden

- name: Configure vaultwarden https site
  ansible.builtin.template:
    src: vaultwarden.j2
    dest: "/etc/nginx/sites-enabled/ssl-vaultwarden"
    mode: "0600"
  vars:
    setup_vaultwarden_ssl_site_url: "{{ setup_vaultwarden_ssl_service_name }}.{{ setup_vaultwarden_ssl_net_host }}"
    setup_vaultwarden_ssl_local_url: "{{ setup_vaultwarden_ssl_service_name }}.{{ ansible_facts['hostname'] }}.lan"
    setup_vaultwarden_ssl_proxy_url: "{{ setup_vaultwarden_ssl_service_host }}:{{ setup_vaultwarden_ssl_service_http }}"
    setup_vaultwarden_ssl_ws_proxy_url: "{{ setup_vaultwarden_ssl_service_host }}:{{ setup_vaultwarden_ssl_service_ws }}"

  notify:
    - Restart nginx
  tags: nginx, vaultwarden
