---
- name: Ensure Samba, UFW, clamav and WSDD are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    pkg:
      - samba
      - samba-client
      - wsdd
      - ufw
      - clamav
    state: present
  tags: samba

- name: Csonfigure Samba
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    validate: /usr/bin/testparm -s %s
    mode: "0600"
  notify:
    - Restart smbd
  tags: samba

- name: Copy over WSDD UFW configuration
  ansible.builtin.copy:
    src: wsdd
    dest: /etc/ufw/applications.d/wsdd
    mode: "0600"
  tags: smaba

- name: UFW open SMB and WSDD
  community.general.ufw:
    rule: allow
    name: "{{ item }}"
  loop:
    - samba
    - wsdd
    - OpenSSH
  tags: samba

- name: Ensure Samba is running
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - smb
    - smbd
    - wsdd
  tags: samba
