---
- name: Playbook for configuring our SSL termination reverse proxy.
  hosts: satori
  vars:
    net_host: "trash-hosting.com"
  tasks:
    - name: Setup reverse proxy and SSL termination
      ansible.builtin.include_role:
        name: setup_nginx_certbot
      vars:
        setup_nginx_certbot_email: "{{ le_email }}"

    - name: Configure LAN sites
      ansible.builtin.include_role:
        name: local_simple_site
      tags: nginx
      vars:
        local_simple_site_host_ip:
          v4: "10.0.0.20"
          v6: "2404:e80:6423:1000::1000:601"
        local_simple_site_services:
          lanragi_artbooks:
            host: "oni.lan"
            port: 8000
          homeassistant:
            host: "oni.lan"
            port: 8001
          shoko:
            host: "oni.lan"
            port: 8004
          betanin:
            host: "oni.lan"
            port: 8005
          komga:
            host: "oni.lan"
            port: 8006
          kanboard:
            host: "oni.lan"
            port: 8008

    # TODO: Public IPv4 is broken due to ISP CGNAT. Next step is to use wireguard on this server to connect to a VPS.
    # An alternative is cloudflare tunneling.
    - name: Configure HTTPs publically exposed sites
      ansible.builtin.include_role:
        name: https_simple_site
      tags: nginx
      vars:
        https_simple_site_host_ip:
          v4: "10.0.0.20"
          v6: "2404:e80:6423:1000::1000:601"
        https_simple_site_net_host: "{{ net_host }}"
        https_simple_site_services:
          kanboard:
            host: "oni.lan"
            port: 8008

    - name: Setup vaultwarden reverse proxy
      ansible.builtin.include_role:
        name: setup_vaultwarden_ssl
      tags: nginx, vaultwarden
      vars:
        setup_vaultwarden_ssl_host_ip:
          v4: "10.0.0.20"
          v6: "2404:e80:6423:1000::1000:601"
        setup_vaultwarden_ssl_net_host: "{{ net_host }}"
        setup_vaultwarden_ssl_service_host: "oni.lan"
        setup_vaultwarden_ssl_service_http: 8007
        setup_vaultwarden_ssl_service_ws: 3012
