---
- name: Playbook for configuring our SSL termination reverse proxy.
  hosts: satori
  vars:
    net_host: "trash-hosting.com"
  tasks:
    - name: Setup reverse proxy and SSL termination
      ansible.builtin.include_role:
        name: setup_nginx_certbot
      vars:
        setup_nginx_certbot_email: "{{ le_email }}"

    - name: Configure LAN sites
      ansible.builtin.include_role:
        name: local_simple_site
      tags: nginx
      vars:
        local_simple_site_host_ip:
          v4: "{{ satori.ip4 }}"
          v6: "{{ satori.ip6 }}"
        local_simple_site_services: "{{ services }}"

    # TODO: Public IPv4 is broken due to ISP CGNAT. Next step is to use wireguard on this server to connect to a VPS.
    # An alternative is cloudflare tunneling.
    - name: Configure HTTPs publically exposed sites
      ansible.builtin.include_role:
        name: https_simple_site
      tags: nginx
      vars:
        https_simple_site_host_ip:
          v4: "{{ satori.ip4 }}"
          v6: "{{ satori.ip6 }}"
        https_simple_site_net_host: "{{ net_host }}"
        https_simple_site_services: "{{ remote_services }}"

    - name: Configure Jellyfin - HTTP Block
      ansible.builtin.copy:
        dest: /etc/nginx/conf.d/jellyfin.conf
        content: "{{ jellyfin_nginx_custom_http }}"
        mode: "0660"
      tags: jellyfin, nginx

    - name: Configure Jellyfin
      ansible.builtin.include_role:
        name: https_simple_site
      tags: nginx, jellyfin
      vars:
        https_simple_site_host_ip:
          v4: "{{ satori.ip4 }}"
          v6: "{{ satori.ip6 }}"
        https_simple_site_net_host: "{{ net_host }}"
        https_simple_site_services:
          jellyfin:
            "{{ services.jellyfin }}"
        https_simple_site_custom: "{{ jellyfin_nginx_custom_server }}"

    - name: Setup vaultwarden reverse proxy
      ansible.builtin.include_role:
        name: setup_vaultwarden_ssl
      tags: nginx, vaultwarden
      vars:
        setup_vaultwarden_ssl_host_ip:
          v4: "{{ satori.ip4 }}"
          v6: "{{ satori.ip6 }}"
        setup_vaultwarden_ssl_net_host: "{{ net_host }}"
        setup_vaultwarden_ssl_service_host: "{{ vaultwarden.host }}"
        setup_vaultwarden_ssl_service_http: "{{ vaultwarden.port }}"
        setup_vaultwarden_ssl_service_ws: "{{ vaultwarden.ws_port }}"
