- hosts: tsukumogami
  roles:
    - common
  tasks:
  - name: Get Roon dependencies
    apt:
      pkg:
      - ffmpeg
      - libasound2
      - cifs-utils
  - name: Download Roon
    get_url:
      url: "https://download.roonlabs.net/builds/roonserver-installer-linuxx64.sh"
      dest: /tmp/roonserver-installer-linuxx64.sh
      mode: 0700
  - name: install roon 
    shell:
      cmd: yes | /tmp/roonserver-installer-linuxx64.sh
      creates: /opt/RoonServer
    tags: roon-install