- name: Playbook for configuring our Samba server, Yatagarasu.
  hosts: yatagarasu
  vars:
    samba_user: "files"
    samba_users: [
      { username: "files", password: yatagarasu_samba_pass }
    ]
  roles:
    - common
    - samba
  tasks:
    - name: Set Samba password
      ansible.builtin.shell: >
        set -e -o pipefail
        && ( pdbedit --user={{ item.username }} 2>&1 > /dev/null )
        || (echo '{{ item.password }}'; echo '{{ item.password }}')
        | smbpasswd -s -a {{ item.username }}
      args:
        executable: /bin/bash
      register: smbpasswd
      changed_when: "'Added user' in smbpasswd.stdout"
      loop: "{{ samba_users }}"
      no_log: true
      notify: restart smbd
      tags: samba,users
